import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const output = 'docs/audit/REPO_TREE.md';
if (!fs.existsSync(path.join(root, output))) fs.writeFileSync(path.join(root, output), '');
const files = [...new Set(execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], { cwd: root, encoding: 'utf8' }).split('\0').filter((file) => file && fs.existsSync(path.join(root, file))))].sort();
const tree = { children: new Map(), count: 0 };
for (const file of files) {
  let current = tree;
  current.count++;
  for (const part of file.split('/')) {
    if (!current.children.has(part)) current.children.set(part, { children: new Map(), count: 0 });
    current = current.children.get(part);
    current.count++;
  }
}
const lines = ['CocEnglish/'];
function render(node, prefix = '', depth = 0) {
  const entries = [...node.children].sort(([a], [b]) => a.localeCompare(b));
  entries.forEach(([name, child], index) => {
    const last = index === entries.length - 1;
    const directory = child.children.size > 0;
    lines.push(`${prefix}${last ? '└── ' : '├── '}${name}${directory ? '/' : ''}${directory && depth >= 2 ? ` (${child.count} files; collapsed)` : ''}`);
    if (directory && depth < 2) render(child, `${prefix}${last ? '    ' : '│   '}`, depth + 1);
  });
}
render(tree);
fs.writeFileSync(path.join(root, output), `# Actual repository tree — 2026-10-10\n\nGenerated by \`node tools/audit/tree.mjs\` from existing Git-tracked and unignored files on disk. Installs, builds, caches and private local environment files are excluded by Git rules. Directories beyond depth three are collapsed with actual file counts; nothing here is a proposed future directory. Total: ${files.length} files. [Baseline inventory](INPUT_INVENTORY.md) predates this refresh; [changed-file manifest](DOCS_MANIFEST.md) owns the diff.\n\n\`\`\`text\n${lines.join('\n')}\n\`\`\`\n`);
console.log(JSON.stringify({ status: 'PASS', files: files.length, output, source: 'Git-tracked/unignored existing paths on disk' }));
