class PreviewState {
  const PreviewState({
    this.bonusGems = 0,
    this.spentGems = 0,
    this.freezes = 0,
    this.timerBoosts = 0,
    this.demoBalanceUsed = false,
    this.claims = const {},
    this.purchases = const {},
    this.following = const {},
    this.reports = const [],
    this.name = 'Sam',
    this.email = 'demo@cocenglish.test',
    this.course = 'English',
    this.sound = true,
    this.reminder = false,
    this.reminderTime = '19:00',
    this.private = false,
    this.leagueOptIn = false,
    this.verified = false,
    this.registered = false,
    this.deletionRequested = false,
    this.questIntroSeen = false,
  });
  final int bonusGems, spentGems, freezes, timerBoosts;
  final bool demoBalanceUsed;
  final Set<String> claims, purchases, following;
  final List<String> reports;
  final String name, email, course, reminderTime;
  final bool sound,
      reminder,
      private,
      leagueOptIn,
      verified,
      registered,
      deletionRequested,
      questIntroSeen;
  PreviewState copyWith({
    int? bonusGems,
    int? spentGems,
    int? freezes,
    int? timerBoosts,
    bool? demoBalanceUsed,
    Set<String>? claims,
    Set<String>? purchases,
    Set<String>? following,
    List<String>? reports,
    String? name,
    String? email,
    String? course,
    String? reminderTime,
    bool? sound,
    bool? reminder,
    bool? private,
    bool? leagueOptIn,
    bool? verified,
    bool? registered,
    bool? deletionRequested,
    bool? questIntroSeen,
  }) => PreviewState(
    bonusGems: bonusGems ?? this.bonusGems,
    spentGems: spentGems ?? this.spentGems,
    freezes: freezes ?? this.freezes,
    timerBoosts: timerBoosts ?? this.timerBoosts,
    demoBalanceUsed: demoBalanceUsed ?? this.demoBalanceUsed,
    claims: Set.unmodifiable(claims ?? this.claims),
    purchases: Set.unmodifiable(purchases ?? this.purchases),
    following: Set.unmodifiable(following ?? this.following),
    reports: List.unmodifiable(reports ?? this.reports),
    name: name ?? this.name,
    email: email ?? this.email,
    course: course ?? this.course,
    sound: sound ?? this.sound,
    reminder: reminder ?? this.reminder,
    reminderTime: reminderTime ?? this.reminderTime,
    private: private ?? this.private,
    leagueOptIn: leagueOptIn ?? this.leagueOptIn,
    verified: verified ?? this.verified,
    registered: registered ?? this.registered,
    deletionRequested: deletionRequested ?? this.deletionRequested,
    questIntroSeen: questIntroSeen ?? this.questIntroSeen,
  );
}
