import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../domain/profile_summary.dart';

const _sampleProfileSummaries = <String, ProfileSummary>{
  'Alex': ProfileSummary(
    userId: 'Alex',
    name: 'Alex',
    username: 'alex',
    joinedYear: 2025,
    xp: 120,
    followingCount: 8,
    streak: 7,
    league: 'Bronze',
    completedLessons: 32,
  ),
  'Maria': ProfileSummary(
    userId: 'Maria',
    name: 'Maria',
    username: 'maria',
    joinedYear: 2025,
    xp: 186,
    followingCount: 14,
    streak: 12,
    league: 'Silver',
    completedLessons: 46,
  ),
  'Lucas': ProfileSummary(
    userId: 'Lucas',
    name: 'Lucas',
    username: 'lucas',
    joinedYear: 2025,
    xp: 98,
    followingCount: 5,
    streak: 4,
    league: 'Bronze',
    completedLessons: 25,
  ),
  'Anna': ProfileSummary(
    userId: 'Anna',
    name: 'Anna',
    username: 'anna',
    joinedYear: 2025,
    xp: 214,
    followingCount: 21,
    streak: 18,
    league: 'Silver',
    completedLessons: 53,
  ),
  'Samira': ProfileSummary(
    userId: 'Samira',
    name: 'Samira',
    username: 'samira',
    joinedYear: 2025,
    xp: 144,
    followingCount: 11,
    streak: 9,
    league: 'Bronze',
    completedLessons: 37,
  ),
  'Sam Lee': ProfileSummary(
    userId: 'Sam Lee',
    name: 'Sam Lee',
    username: 'sam.lee',
    joinedYear: 2025,
    xp: 165,
    followingCount: 12,
    streak: 10,
    league: 'Silver',
    completedLessons: 41,
  ),
  'Noah': ProfileSummary(
    userId: 'Noah',
    name: 'Noah',
    username: 'noah',
    joinedYear: 2025,
    xp: 76,
    followingCount: 4,
    streak: 3,
    league: 'Bronze',
    completedLessons: 19,
  ),
  'Emma': ProfileSummary(
    userId: 'Emma',
    name: 'Emma',
    username: 'emma',
    joinedYear: 2025,
    xp: 201,
    followingCount: 18,
    streak: 15,
    league: 'Silver',
    completedLessons: 50,
  ),
  'James Smith': ProfileSummary(
    userId: 'James Smith',
    name: 'James Smith',
    username: 'james.smith',
    joinedYear: 2025,
    xp: 132,
    followingCount: 9,
    streak: 6,
    league: 'Bronze',
    completedLessons: 34,
  ),
};

final profileSummaryProvider = Provider.family<ProfileSummary?, String>(
  (_, userId) => _sampleProfileSummaries[userId],
);
